---

- name: Ubuntu desktop environment playbook
  hosts: localhost
  roles:
    # Server roles
    - { role: docker, become: true }
    - { role: nodejs, become: true }
    - { role: ssh, become: true }
    # Desktop roles
    - { role: chromium, become: true }
    - { role: dbeaver, become: true }
    - { role: filezilla, become: true }
    - { role: gdrive, become: true }
    - { role: vagrant, become: true }